"""create user_preferences table

Revision ID: 27abff253fef
Revises: bd3d4332d610
Create Date: 2026-06-11 17:10:30.162088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27abff253fef'
down_revision: Union[str, None] = 'bd3d4332d610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_level', sa.String(), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tools', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('goals', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('content_style', sa.String(), nullable=True),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
